---
name: Linter

# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-linter:
    name: lint-code-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full list of changes needed.

      - name: Run Super Linter
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
